### ISSUE TITLE
Unclear syntax for multiple line answer questions

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#10]
`[--multiple-answer-0--] ... [--multiple-answer-9--]`

[This](https://github.com/openrightsgroup/alidade/wiki/form-editing#text-areas) doesn't work at the moment. Can we have some clearer examples?

**Comment by dantheta** [comment]
The original code only enabled multi-answer fields on a fixed list of pages.  I've removed this restriction, so it should be good now.  We'll need to fix up the answer-saving code for this as well, but I'll do that when I'm adding support for the other option types.

**Comment by dantheta** [comment]
Tested and deployed.
