### ISSUE TITLE
Checkboxes are rendering with a bulletpoint underneath

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#11]
With the example given [in the docs](https://github.com/openrightsgroup/alidade/wiki/form-editing#option-checkboxes), checkboxes render with a bullet point underneath.

<img width="517" alt="CleanShot 2019-09-27 at 13 00 45@2x" src="https://user-images.githubusercontent.com/6547979/65767794-e0eac580-e126-11e9-8372-b03a21d7ecfd.png">

Taking the \<li\>s out removes the bulletpoints but then the checkbox is then not vertically-aligned to the middle. It's also bad HTML.

**Comment by dantheta** [comment]
Added a style suppressing bullet points for lists inside the main form.
