### ISSUE TITLE
Example needed for Optional selection panels

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#12]
Can we have an example of how Optional selection panels work in the docs?

https://github.com/openrightsgroup/alidade/wiki/form-editing#optional-selection-panels-within-pages

Not clear why this isn't working for example

```
[--choicepanel|panel[1]--]
[--choicebutton|internal_id[1]|Public title--]
[--choicebutton|internal_id[2]|Public title--]
[--endchoicepanel--]

```

**Comment by dantheta** [comment]
Added example to the wiki page.  The panel and internal IDs aren't expected to have squarebrackets in them -  those are typically used to pass array fields to PHP backends.
