### ISSUE TITLE
Array Answer fields

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#16]
Ideally we would have an array answer field that is something like this.

Mockup
<img width="485" alt="CleanShot 2019-10-01 at 17 02 18@2x" src="https://user-images.githubusercontent.com/6547979/65979487-41eb0400-e46d-11e9-929e-f5a9d62a6551.png">

A working version – see qu 2 here:
https://generator.projectsbyif.com

**Comment by dantheta** [comment]
This has been added using default alpaca options.  Please let me know if there are any defaults from the alpaca doc that you'd like added:

http://www.alpacajs.org/docs/fields/array.html

The wiki placeholder doc has been updated.

**Comment by edjw** [comment]
Thanks Dan. Any chance that when the form fields are being typed into, tapping Enter would add the contents of the field to the array? It would need to override the current behaviour which is to move to the next slide

**Comment by edjw** [comment]
Tapping Enter will be a really common behaviour here I think. ATM it moves to the next slide and gives the error

```
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'project' cannot be null
)

```

> Thanks Dan. Any chance that when the form fields are being typed into, tapping Enter would add the contents of the field to the array? It would need to override the current behaviour which is to move to the next slide

**Comment by dantheta** [comment]
Closing in favour of follow on ticket #37.
