### ISSUE TITLE
Problem with radio buttons

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#17]
On this page, I'm using the following markup

http://167.99.198.95/manage/slide/41

http://167.99.198.95/project/slide/0.1

```
<div class="row">
    <div class="col-md-6">
       [--radio|option1|Yes, the project involves personal data.--]
    </div>
    <div class="col-md-6">
       [--radio|option2|No, I do not believe the product handles personal data.--]
    </div>
</div>
```

But it looks like this

<img width="452" alt="CleanShot 2019-10-01 at 17 16 46@2x" src="https://user-images.githubusercontent.com/6547979/65980539-46b0b780-e46f-11e9-8757-d1bfdca6dde7.png">

**Comment by dantheta** [comment]
The regex wasn't matching the comma or full stop.  I've expanded the allowed character set to match those in the radio macro.
