### ISSUE TITLE
Sideboxes not always rendering

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#18]
The boxes on the right side aren't always rendering — on this page for example.

http://167.99.198.95/project/slide/0.1
http://167.99.198.95/manage/slide/41

One sidebox renders and one doesn't. I'm confused

**Comment by dantheta** [comment]
The sidebox renderer previously required `[--box--]` and `[--endbox--]` to be on the same line.  The sidebox injection rejex has been updated to allow the start and end placeholders to be on separate lines.
