### ISSUE TITLE
Full page refresh when move slide up or down

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#2]
Is there any way of not having a full org refresh when a slide is moved up or down?

I think it could get quite slow to edit as is

**Comment by dantheta** [comment]
If there are going to be larger numbers of slides within a step (n > 8), then using drag & drop may be more appropriate.  The 1/up and 1/down was just easy to write.

**Comment by edjw** [comment]
This seems to be fixed now. You get this error if you move the last slide down or the first slide up but I think we can live with that.

```
Warning: Creating default object from empty value in /var/www/html/app/model/slidelist.model.php on line 108
Fatal
[ERROR CODE 666]
Invalid Update Parameter. (model.class.php, 130)
```
