### ISSUE TITLE
Improve answer storage

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/alidade#20]
The current slide answer save code uses text serialization to compound multiple answer fields into a single database field, and the display code splits this field up again for display.

This doesn't currently handle slides which have a mixture of control types (textarea, multi-textarea, checkbox, radio button).

The form save code should be extended to create a struct/document which is serialized into the single database field, and the display code should be able to match fields from the serialized struct to populate the fields correctly when viewed.

The serialized struct should support a mixture of control types:
* Multi-text area
* Checkboxes
* Multiple groups of radio buttons.

**Comment by dantheta** [comment]
This feature is now mostly complete and deployed to the staging server.  There are some placeholder syntax changes for checkboxes, detailed on the project wiki.

**Comment by edjw** [comment]
Can we recall specific answers from previous slides where that slide has multiple questions on it now?

**Comment by dantheta** [comment]
Yep, that's fixed now.  I've added the updated syntax to the formatting wiki page.

**Comment by edjw** [comment]
How does this work if there are multiple answers on the specified step/slide?
