### ISSUE TITLE
Step text not being pulled in

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#21]
Step title and text aren't being pulled in

![CleanShot 2019-10-03 at 15 31 21](https://user-images.githubusercontent.com/6547979/66136173-ef3b5480-e5f2-11e9-9e28-32f9c0bd9e05.gif)

**Comment by dantheta** [comment]
I'm not completely sure that the original code did pull in the step title and description here.  I think it may have been using a slide in step 1, position 0 which is exclde from the menu listing (but is still accessed by clicking on the step heading link in the left sidebar.  I've had a look in the original codebase, and I can't find any code for displaying the title and description fields from the step record.

**Comment by edjw** [comment]
Ok I don't mind if we continue to have a slide in 1.0. Think this needs a bit of work to make the first slide 1.0 though?

**Comment by dantheta** [comment]
When creating a new step, the first available slide position is now 0.  It may prove a little tricky to get a slide into position 0 for a step that already exists.  I'll look into it.

**Comment by edjw** [comment]
The Step titles in the sidebar should be the Step title from the admin area. Then clicking on that Step title should go to a page (probably x.0) that shows the Step title and the Step description from the admin area)

<img width="641" alt="CleanShot 2019-11-08 at 13 50 14@2x" src="https://user-images.githubusercontent.com/6547979/68481285-b401f600-022e-11ea-8886-8e075af54a6a.png">

<img width="630" alt="CleanShot 2019-11-08 at 13 50 23@2x" src="https://user-images.githubusercontent.com/6547979/68481298-bb290400-022e-11ea-8b1e-44afc119458b.png">

**Comment by dantheta** [comment]
Position 0 of each step now shows the step title and description.  I've updated the staging DB so that the slides start at position 1 in each step.
The sidebar now uses the step titles too.
