### ISSUE TITLE
Non-existent Margins between buttons 

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#24]
At some point we need to fix the CSS on these buttons

<img width="728" alt="CleanShot 2019-10-03 at 16 42 31@2x" src="https://user-images.githubusercontent.com/6547979/66142147-d8016480-e5fc-11e9-98a4-903b78e4622e.png">

**Comment by dantheta** [comment]
I've added a temporary nbsp in the meantime.

**Comment by javierruizorg** [comment]
Is this something we can live with? @edjw

**Comment by dantheta** [comment]
It'll only take 10 mins to fix, just haven't got to it yet.

On 12 November 2019 14:34:17 GMT, javierruizorg <notifications@github.com> wrote:
>Is this something we can live with? @edjw 

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
