### ISSUE TITLE
Show multiple array inputs and pull in previous answers

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#28]
On slide 2.5, we ask the user to write a list of who might receive data for each kind of data they say they collect.

They say on 2.1 which types of data they collect.

Then on 2.5, we need to recall each of those types of data, and give an array input for each type of data

How can we do this?

Attempt to say what I mean in a hybrid of JS and Python…

```
for type_of_data_collected in all_types_of_data_collected {
    show type_of_data_collected;
    show array_input;
}
```

**Comment by dantheta** [comment]
I think this case suits https://github.com/openrightsgroup/alidade/wiki/Data-categories-(Complex-forms)---proposal too.  The data from the previous form is passed to server-side code that produces a form layout for alpaca.

**Comment by dantheta** [comment]
http://www.alpacajs.org/docs/fields/optiontree.html

**Comment by dantheta** [comment]
Updated https://github.com/openrightsgroup/alidade/wiki/Data-categories-(Complex-forms)---proposal

**Comment by dantheta** [comment]
I've hooked up the demo to slides 2.1 and 2.5 on the staging site.  If you fill in 2 or 3 categories in the array field on 2.1, you should be able to see them as expanders on slide 2.5 and fill in an array list for each category on that slide.  Saving the data works, but re-displaying it doesn't quite work yet.

**Comment by dantheta** [comment]
The form definition can be seen in https://github.com/openrightsgroup/alidade/blob/master/app/controller/forms/2.1.json, and the transformation is in https://github.com/openrightsgroup/alidade/blob/master/app/controller/projectcontroller.ctrl.php#L231

**Comment by edjw** [comment]
@dantheta This should be the absolute priority now.

On slide 2.1 we ask for a list of types of data you collect with an array input with field-id of "data_collected"

On slides 2.2, 2.3, and 2.4, we need need to pull in each answer from data_collected and for each answer, ask several more questions. 

So it has to be flexible. We need to recall the answers, and then nested further questions within an area dedicated to each individual answer

Like how you mocked up here
<https://raw.githubusercontent.com/wiki/openrightsgroup/alidade/collapser.png>

Tried to lay out an example structure here too.

<img width="643" alt="CleanShot 2019-11-13 at 17 38 50@2x" src="https://user-images.githubusercontent.com/6547979/68789028-7a6d2880-063c-11ea-9b12-8b868f82b661.png">

**Comment by dantheta** [comment]
2.2 and 2.3 now have custom forms loaded using the data from 2.1.  I couldn't see where slide 2.4 should have a repeated group of fields.

**Comment by edjw** [comment]
@dantheta — How do we add the custom forms to those pages? It looks to be hardcoded? But it's not showing up in 2.2 or 2.3

**Comment by dantheta** [comment]
They're added as files in app/controllers/forms/<slilde>.json, and invoked using

```
[--alpaca|2.3--]
```
(for slide 2.3)

They're still there on slide 2.3, but seem to have disappeared from 2.2.

There's a small amount of hardcoded logic for slides which have the multiplied fields:
https://github.com/openrightsgroup/alidade/blob/master/app/controller/projectcontroller.ctrl.php#L253

You need to have added some data categories on slide 2.1 before anything appears.

**Comment by dantheta** [comment]
I've added the form back into slide 2.2.  I'll update the wiki with the markup and requirements.

**Comment by dantheta** [comment]
The placeholder for this has been changed to `[--customform|<name>--]`.

Instead of creating schema for alpaca, I'm generating forms with PHP.  It's much easier to write, and more reliable for saving and loading values.

Do we have a list of the lawful bases for slide 2.3?

**Comment by dantheta** [comment]
I've got the lawful bases now.

The repeat fields have been reimplemented using PHP and are now deployed to the staging site.

If you need a custom form added to slide 2.4 (mentioned above), please open a new issue.
