### ISSUE TITLE
Sidebar not showing all slides

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#29]
I would expect these titles to show up in the sidebar.

<img width="727" alt="CleanShot 2019-11-01 at 16 32 45@2x" src="https://user-images.githubusercontent.com/6547979/68039999-3fc2d200-fcc5-11e9-831f-45516ce04d77.png">

But some titles are missing (eg Step 3 Context and Space or Step 4 - Technical) and some empty steps are showing up.

<img width="283" alt="CleanShot 2019-11-01 at 16 31 12@2x" src="https://user-images.githubusercontent.com/6547979/68039921-1144f700-fcc5-11e9-99fa-877aa3832d2b.png">

I imagine the weird numbering in the admin will be useful to debugging this

**Comment by dantheta** [comment]
I've fixed that by renumbering.  There's still some weirdness in step 4, it doesn't seem to like the zero-indexed positions, although it isn't clear how the step descriptions get displayed otherwise.

**Comment by edjw** [comment]
These are the slides that I think have a problem

4.0, 5.0, 6.0, 7.0 have questions but no other x.0 slides do. These slides having titles. Those titles should be shown in a section on the sidebar.

We want to use x.0 for to introduce the user to that section but don’t show questions on those slides.

4.5, 5.6, 7.10 don’t exist but they’re showing in sidebar. Remove these.

**Comment by dantheta** [comment]
Since #21 was done, slides no longer need to start at position 0 inside a step.  Position 0 in a step shows the step title and description.  I've moved any slides at position  0 to position 1 and moved everything else up.

Are you seeing any other slide numbering oddities now?  4.5, 5.6, 7.10 all seem OK now.

**Comment by javierruizorg** [comment]
@edjw I think we can close, please check
