### ISSUE TITLE
Error when try to delete a Step

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#3]
The following error is shown when you try to delete a Step. We can't delete steps at the moment.
```
Fatal
[ERROR CODE 601]
Could not execute query. Cannot delete or update a parent row: a foreign key constraint fails (`alidade`.`slide_list`, CONSTRAINT `fkSlidelistStep` FOREIGN KEY (`step`) REFERENCES `steps` (`idsteps`) ON DELETE NO ACTION ON UPDATE NO ACTION) (model.class.php, 183)
```

**Comment by dantheta** [comment]
The data model previously insisted that all slides were removed from a step before it can be removed (Although the error reporting also doesn't work properly).

I've converted the foreign key constraint to automatically delete slides and answers when a step is removed.

**Comment by dantheta** [comment]
Deployed.
