### ISSUE TITLE
Weird routing thing in create new slide route

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#30]
`http://domain.tld/manage/slide/any-string-here` has the same effect as `http://domain.tld/manage/slide/new`

Don't think this is necessarily a problem but thought I'd raise it in case you can see a problem with that. I've labelled it as wontfix but remove that if you think it should be fixed

**Comment by dantheta** [comment]
I don't think this is harmfull, and may go away when we get better 404 handling.  I'll close this one for now, but we can refer back to it if needed.
