### ISSUE TITLE
What's the URL for static pages?

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#32]
What's the URL for a static page where the URL was specified as 'quick-tips'? Can we document the answer in the wiki?

http://167.99.198.95/page/quick-tips just gives:

```
Fatal error: Uncaught Error: Wrong parameters for Error([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/html/lib/main.php:73 Stack trace: #0 /var/www/html/lib/main.php(73): Error->__construct('502', 'Controller/Meth...') #1 /var/www/html/lib/main.php(112): init() #2 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #3 {main} thrown in /var/www/html/lib/main.php on line 73
```

**Comment by dantheta** [comment]
It looks like the static page database content isn't plumbed in at all.  The /page/research and /page/six-rules use the routing mechanism in the main code, but the page content is hardcoded in templates (https://github.com/openrightsgroup/alidade/blob/master/app/view/page/research.php and https://github.com/openrightsgroup/alidade/blob/master/app/view/page/six_rules.php)

**Comment by dantheta** [comment]
The wrong parameters error is caused by a bug - the original codebase used an Error class for exceptions, but this has become an inbuilt class in PHP 7.0.  There's a separate bug for that.

**Comment by dantheta** [comment]
These are all plumbed in now.  The URLs for a particular page are shown in the admin panel for page contents.
