### ISSUE TITLE
Adding and deleting static pages

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#33]
Can we have a GUI to add and delete static pages? The one you've used for slides and steps should be fine

<img width="268" alt="CleanShot 2019-11-01 at 17 18 55@2x" src="https://user-images.githubusercontent.com/6547979/68042811-b236b080-fccb-11e9-8cff-cd2ecaa79810.png">

**Comment by dantheta** [comment]
Basic page add,edit and delete added.

**Comment by edjw** [comment]
Not a priority. But it would be nice if the next page after adding or deleting a static Pages was the Pages tab rather than Steps tab. Same with deleting a Slide
