### ISSUE TITLE
Make it easier to see and click on the Delete buttons on Slides and Steps

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#34]
I don't think we need to prioritise this. It might be quite hard for a new user to work out how to delete button on slides and steps. Maybe it could just go in the same box as the Move Up and Move Down buttons

![CleanShot 2019-11-01 at 17 22 31](https://user-images.githubusercontent.com/6547979/68043012-35f09d00-fccc-11e9-8e94-5ccbb7e27440.gif)

**Comment by dantheta** [comment]
I've reworked the admin page into tabs for pages, slides, steps and management functions, and the entries are now laid out in a table with the links always visible.  Much easier to use than the hover links.
