### ISSUE TITLE
Adding strings or <style> tags after http://167.99.198.95/project/slide renders

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#36]
I mentioned this in #31 but this deserves an issue of its own

You can make our version of alidade say anything like this.

http://167.99.198.95/project/slide/I%20can%20make%20this%20say%20anything gives this

<img width="775" src="https://user-images.githubusercontent.com/6547979/68041754-2754b680-fcc9-11e9-9302-12980c53b082.png">

But it also renders CSS. Like this.

http://167.99.198.95/project/slide/%3Cstyle%3E*%20%7Bbackground-color:%20blue;%7D%3C/style%3E

This could just look bad. But could also load 3rd party data by loading background images as url

Inserting <script> doesn't work thankfully
http://167.99.198.95/project/slide/%3Cscript%3Ealert(%22hello%22);%3C/script%3E

**Comment by dantheta** [comment]
There may be quite a lot of scope for XSS, since the templating layer does not enforce escaping based on origin of content.  I think the 404 sprinkling may help, but this could be a longer piece of work.  We can make sure that the user-supplied content in the forms is safe as part of one of the other issues.

**Comment by dantheta** [comment]
Most of the functions that are responsible for rendering user data have been switched over to inline or file-based twig templates.  The main slide template is still raw PHP, but this is probably going to be converted to allow better sidebox handling.

**Comment by dantheta** [comment]
Form controls are now rendered by template blocks, which implements proper output escaping.
