### ISSUE TITLE
Allow multiple radio buttons on the same page

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#38]
The wiki says, “Currently there can only be one set of radio buttons on a slide (with all radio buttons being mutually exclusive), but this is likely to change soon.”

This needs to be fixed asap. I think it should be fine now we've gone to json for saving user responses but has to be in place

**Comment by dantheta** [comment]
Code and wiki updated.  https://github.com/openrightsgroup/alidade/wiki/Form-Editing#radio-buttons

Existing radio buttons will need to be updated to use the three-parameter format.

If compatibility with existing saved records is required, use the field name `choice`.
