### ISSUE TITLE
Add new slides is broken

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#4]
Can't add new slides using the GUI. See gif below

![CleanShot 2019-09-25 at 11 46 43](https://user-images.githubusercontent.com/6547979/65594367-8288e000-df8a-11e9-8a52-811cef6c16a0.gif)

**Comment by edjw** [comment]
@dantheta – This would be a priority to fix Dan as we can't make progress otherwise

**Comment by dantheta** [comment]
Really strange - this one is working on the dev server, but not on the live server.
The description field wasn't being posted when the form is saved.  I've changed the div to a textarea, and it's working now.

**Comment by edjw** [comment]
I'm now getting the following error when adding Steps. It's the same error as in #6 

```
Fatal
[ERROR CODE 666]
Invalid Update Parameter. (model.class.php, 130)
```

**Comment by dantheta** [comment]
The screenshot shows the step edit screen - I fixed errors on that last night. Can you confirm which screen (step/slide) is now giving the error on saving?



On 25 September 2019 11:49:43 BST, edjw <notifications@github.com> wrote:
>Assigned #4 to @dantheta.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/alidade/issues/4#event-2661207291

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edjw** [comment]
Sorry wasn't clear enough. When I try to create a new Step, I'm getting this error 666 invalid update parameter

**Comment by dantheta** [comment]
Make sure you fill in name and description. Both fields are required.

There's some dodgy field filtering code in there that needs to be removed.

On 26 September 2019 15:42:31 BST, edjw <notifications@github.com> wrote:
>Sorry wasn't clear enough. When I try to create a new Step, I'm getting
>this error 666 invalid update parameter
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/alidade/issues/4#issuecomment-535536396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edjw** [comment]
I'm getting the error even when I fill out both name and description

**Comment by dantheta** [comment]
Definitely fixed now.
