### ISSUE TITLE
Recap pages

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#44]
Can we have some markup we can put in that inserts all questions and answers from the current step into the recap page?

For the final slide of each step, we'd like to have a recap page which shows all the questions and the user's responses to those questions.

**Comment by javierruizorg** [comment]
These pages exist in the original Alidade. They also include a pdf button to print WIP report.

In our version we also want to display **warning messages** triggered by certain responses or lack thereof.

**Comment by dantheta** [comment]
The recap is added automatically in slides of type _recap_, so there's no need to add an extra markup option.  I'm just working on the automatic markup display now.

**Comment by dantheta** [comment]
The recap slide at the end of step 2 is now working, and shows all of the content along with answers (currently styled in gray, but that will get tidied). 

 If you'd like to, you could do a demo run-through with step 2, giving relistic answers to questions and then see how the recap step looks. If you spot any styling problems or content glitches, feel free to add them to issue 44. Thanks!

**Comment by dantheta** [comment]
Choicepanels and boxes are not being handled correctly, showing extra answerpanels in the recap stage.

**Comment by dantheta** [comment]
This should be fixed now.  If any extraneous answer panels still appear, you can use browser developer tools to point at the panel and the 'data-field' attribute should show which form field / control caused the panel to appear.

Sideboxes are now properly excluded from the recap output, so it should look a lot clearer too.
