### ISSUE TITLE
Recalling previous answers

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#45]
Recalling an answer from a page with just a single question on it isn't working. For example `[--prev|2.13--] ` on http://167.99.198.95/project/slide/2.14/?p=2d889599cb0e428441ee4c139db50370

We also need to be able to recall answers from previous slides that have multiple questions on it as well.

**Comment by dantheta** [comment]
The syntax for that placeholder was changed to accommodate multi-answer slides.
See https://github.com/openrightsgroup/alidade/wiki/Form-Editing#previous-answer
