### ISSUE TITLE
"Save progress" button in all pages

### ISSUE THREAD

**Issue by javierruizorg** [openrightsgroup/alidade#46]
Users need clarity on when data get saved. Right now it seems to be after the "Next section button" is clicked.

We need “save data” buttons if they want to take a break without clicking next.  

This is really important for some slides where we ask users to go and use other tools or do an exercise before inputting the questionnaire.

**Comment by edjw** [comment]
Can we save automatically at some event rather than with a user button? Maybe when an input field loses focus?

**Comment by dantheta** [comment]
I'm not so keen on the automatic save.  It leaves no way for users to back out of a set of changes in progress.  Maybe we could change the "next" button to "save and continue", which is what it's really doing?

**Comment by javierruizorg** [comment]
Sounds good to me!

--

**Comment by javierruizorg** [comment]
This save Button should also is linked to the triggering of the tick box in the left menu I raised in another issue

--

**Comment by javierruizorg** [comment]
We agree that next button is better
