### ISSUE TITLE
Clarify and document numbering of "optionfield" and "option" in radio buttons

### ISSUE THREAD

**Issue by javierruizorg** [openrightsgroup/alidade#50]
#17 has been fixed but we need to document how these fields and values should be named and how to recall them. Do they need to be unique across the whole system or only for each slide?

Should we use a numbering system for optionfields following the page? 

e.g. page 2.5

[--radio|2.5.1|option1|Choose Option 1--]
[--radio|2.5.1|option2|Choose Option 2--]

[--radio|2.5.2|option1|Choose Option 1--]
[--radio|2.5.2|option2|Choose Option 2--]

This is a problem if we delete or move slides. Do we make a convention?

**Comment by dantheta** [comment]
The numbers don't mean anything, they were just for example purposes.

They only need to be unique within the slide.

There doesn't need to be a numbering system for them, the names can be chosen based on the question that they're associated with.  For instance, on slide 2.5, you could use:

Do you share or disclose personal data to any other people or organisations?
```
[--radio|share_personal_data|yes|Yes--]
[--radio|share_personal_data|no|No--]
```

Does the project involve transfers of personal data outside the EU or EEA?
```
[--radio|share_outside_eu|yes|Yes--]
[--radio|share_outside_eu|no|No--]
```

I've added this example to the wiki page.
