### ISSUE TITLE
Fatal error when renaming Step and changing copy

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#6]
I can't update steps at the moment

```
Fatal
[ERROR CODE 666]
Invalid Update Parameter. (model.class.php, 130)
```

**Comment by edjw** [comment]
@dantheta – This would be a priority to fix Dan as we can't make progress otherwise

**Comment by dantheta** [comment]
This was the same cause as #4 , and should be fixed now.

**Comment by dantheta** [comment]
Found and fixed a few more form issues.
