### ISSUE TITLE
On frontend, all Steps are called Step 1

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#7]
![CleanShot 2019-09-25 at 12 03 24@2x](https://user-images.githubusercontent.com/6547979/65595382-99c8cd00-df8c-11e9-8ad9-0c2ae8f55fb8.png)

**Comment by dantheta** [comment]
The title is fixed now.  It appears that deleting a step will leave a hole in the sequence number. I'll add a new issue for that.
