### ISSUE TITLE
Nested choice panels

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#73]
Can we nest choice panels so you can have choice panels inside other choice panels?

This should be documented so we can reproduce it

I think you've done quite a lot of work on this already Dan. Just putting this here to track the progress

**Comment by dantheta** [comment]
These could prove tricky when the page is re-visited, as we need to store the state of the choice buttons.  We'll see how it goes, but it might be easier to reimplement the choicebuttons as radio buttons so that the main page load/save can take care of restoring their state.

**Comment by dantheta** [comment]
Nested panels are now permitted.  Wiki updates in progress.

Note that to use nested panels, all choicepanels on a slide must use the form:
```
[--choicepanel|main--]

  [--choicepanel|sub--]
  [--endchoicepanel|sub--]

[--endchoicepanel|name--]
```
