### ISSUE TITLE
Deleting a step/slide leaves a gap in the step titles

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/alidade#8]
* Step 1
* Step 2 <-- delete this
* Step 3

Results in:

* Step 1
* Step 3

**Comment by dantheta** [comment]
This is fixed by allowing the slide position to be saved directly from the edit form.  This can also be used to fix the gaps in the sidebar menu.

**Comment by javierruizorg** [comment]
Deleting slide still leaves a gap in the side menu. Manually changing the slide number will move it but it simply leaves a gap where the slide was before.

See 2.3. I deleted 2.4 and now we an empty space in the menu.

![image](https://user-images.githubusercontent.com/1063057/68689468-4d4f4600-0568-11ea-9469-26cecf3d52c2.png)

**Comment by dantheta** [comment]
The workaround was to change all of the slides following the deleted one.  I've added code that does that now.  The gap has been fixed in the database.
