### ISSUE TITLE
Errors when clicking 'Next' button on slides

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#9]
```
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'project' cannot be null
)


Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/app/controller/projectcontroller.ctrl.php:225 Stack trace: #0 /var/www/html/lib/main.php(71): Projectcontroller->slide('1.8', '') #1 /var/www/html/lib/main.php(112): init() #2 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #3 {main} thrown in /var/www/html/app/controller/projectcontroller.ctrl.php on line 225

```

![CleanShot 2019-09-26 at 15 33 34](https://user-images.githubusercontent.com/6547979/65697592-1cc45300-e073-11e9-943d-30315ea6e01c.gif)

**Comment by edjw** [comment]
On [1.6](http://167.99.198.95/project/slide/1.6/?p=), the error is…

```
 Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/app/controller/projectcontroller.ctrl.php:181 Stack trace: #0 /var/www/html/lib/main.php(71): Projectcontroller->slide('1.6', '') #1 /var/www/html/lib/main.php(112): init() #2 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #3 {main} thrown in /var/www/html/app/controller/projectcontroller.ctrl.php on line 181
```

**Comment by edjw** [comment]
Could it be to do with this? Or is this a separate thing? The path for the slides always say 1.X even when it's in the 2nd or 3rd step

![CleanShot 2019-09-26 at 15 44 36](https://user-images.githubusercontent.com/6547979/65698643-bdffd900-e074-11e9-927e-8851a1fb4aec.gif)

**Comment by dantheta** [comment]
Separate thing, I think, but I'll check more tonight.

The step number in the sidebar headings should be fixed already.

On 26 September 2019 15:44:08 BST, edjw <notifications@github.com> wrote:
>Could it be to do with this? Or is this a separate thing? The path for
>the slides always say 1.X even when it's in the 2nd or 3rd step
>
>
>
>
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/alidade/issues/9#issuecomment-535537222

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edjw** [comment]
Yes the step number thing is fixed. But the URL path for, for example, Step **2** – question 1 is **1**.1 instead of **2**.1

**Comment by dantheta** [comment]
URL path is fixed now (although that's not what this ticket was originally for :) ).

**Comment by dantheta** [comment]
The slide progression with _next_ buttons is going to take a bit more time to fix up.  I've added a test script for the management pages, so you should be able to edit content in the management screens and preview it in the frontend by navigating directly to the pages.

**Comment by edjw** [comment]
I'm getting the below error moving from http://167.99.198.95/project/slide/0.1 to http://167.99.198.95/project/slide/0.2

```
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/app/controller/projectcontroller.ctrl.php:226 Stack trace: #0 /var/www/html/lib/main.php(71): Projectcontroller->slide('0.2', '') #1 /var/www/html/lib/main.php(112): init() #2 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #3 {main} thrown in /var/www/html/app/controller/projectcontroller.ctrl.php on line 226

```

**Comment by dantheta** [comment]
This looks like it's working for me now.  Can you re-test?

**Comment by javierruizorg** [comment]
I think this is fixed. @edjw can you check and close?
